ALTER TABLE `pi_ratepay_settings` ADD `LIMIT_MAX_B2B` INT(5) NOT NULL AFTER `LIMIT_MAX`;
ALTER TABLE `pi_ratepay_settings` ADD `MIN_RATE` INT(5) NOT NULL DEFAULT 0 AFTER `MONTH_ALLOWED`;
ALTER TABLE `pi_ratepay_settings` ADD `INTEREST_RATE` FLOAT(5) NOT NULL DEFAULT 0 AFTER `MIN_RATE`;