ALTER TABLE `pi_ratepay_order_details` ADD `UNIQUE_ARTICLE_NUMBER` VARCHAR(50) NOT NULL AFTER `ARTICLE_NUMBER`;

ALTER TABLE `pi_ratepay_settings` CHANGE `PAYMENT_FIRSTDAY` `PAYMENT_FIRSTDAY` VARCHAR(5) NOT NULL DEFAULT '0';

ALTER TABLE `pi_ratepay_orders` DROP `TRANSACTION_SHORT_ID`;