<?php

/**
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * @category  PayIntelligent
 * @package   PayIntelligent_RatePAY
 * @copyright (C) 2011 PayIntelligent GmbH  <http://www.payintelligent.de/>
 * @license	http://www.gnu.org/licenses/  GNU General Public License 3
 */
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                  => 'UTF-8',
    'SHOP_MODULE_GROUP_PI_RATEPAY_GENERAL'     => 'Allgemein',
    'SHOP_MODULE_GROUP_PI_RATEPAY_GERMANY'     => 'Deutschland',
    'SHOP_MODULE_GROUP_PI_RATEPAY_AUSTRIA'     => 'Österreich',
    'SHOP_MODULE_GROUP_PI_RATEPAY_SWITZERLAND' => 'Schweiz',
    'SHOP_MODULE_GROUP_PI_RATEPAY_NETHERLAND'  => 'Niederlande',
    'SHOP_MODULE_blRPLogging'                   => 'Vorgänge protokollieren',
    'SHOP_MODULE_blRPAutoPaymentConfirm'        => 'Auto Payment Confirm',
    'SHOP_MODULE_blRPInvoiceActive'             => 'RatePAY Rechnung aktiv',
    'SHOP_MODULE_blRPInvoiceSandbox'            => 'Sandbox (Testmodus)',
    'SHOP_MODULE_sRPInvoiceProfileId'           => 'Profil ID',
    'SHOP_MODULE_sRPInvoiceSecret'              => 'Security Code',
    'SHOP_MODULE_blRPInstallmentActive'         => 'RatePAY Ratenzahlung aktiv',
    'SHOP_MODULE_blRPInstallmentSandbox'        => 'Sandbox (Testmodus)',
    'SHOP_MODULE_sRPInstallmentProfileId'       => 'Profil ID',
    'SHOP_MODULE_sRPInstallmentSecret'          => 'Security Code',
    'SHOP_MODULE_blRPElvActive'                 => 'RatePAY SEPA-Lastschrift aktiv',
    'SHOP_MODULE_blRPElvSandbox'                => 'Sandbox (Testmodus)',
    'SHOP_MODULE_blRPElvIbanOnly'               => 'Only allow IBAN',
    'SHOP_MODULE_sRPElvProfileId'               => 'Profil ID',
    'SHOP_MODULE_sRPElvSecret'                  => 'Security Code',
    'SHOP_MODULE_blRPAustriaInvoice'            => 'RatePAY Rechnung aktiv',
    'SHOP_MODULE_blRPAustriaInvoiceSandbox'     => 'Sandbox (Testmodus)',
    'SHOP_MODULE_sRPAustriaInvoiceProfileId'    => 'Profil ID',
    'SHOP_MODULE_sRPAustriaInvoiceSecret'       => 'Security Code',
    'SHOP_MODULE_blRPAustriaInstallment'        => 'RatePAY Ratenzahlung aktiv',
    'SHOP_MODULE_blRPAustriaInstallmentSandbox' => 'Sandbox (Testmodus)',
    'SHOP_MODULE_sRPAustriaInstallmentProfileId'=> 'Profil ID',
    'SHOP_MODULE_sRPAustriaInstallmentSecret'   => 'Security Code',
    'SHOP_MODULE_blRPAustriaElv'                => 'RatePAY SEPA-Lastschrift aktiv',
    'SHOP_MODULE_blRPAustriaElvSandbox'         => 'Sandbox (Testmodus)',
    'SHOP_MODULE_sRPAustriaElvProfileId'        => 'Profil ID',
    'SHOP_MODULE_sRPAustriaElvSecret'           => 'Security Code',
    'SHOP_MODULE_blRPSwitzerlandInvoice'        => 'RatePAY Rechnung aktiv',
    'SHOP_MODULE_blRPSwitzerlandInvoiceSandbox' => 'Sandbox (Testmodus)',
    'SHOP_MODULE_sRPSwitzerlandInvoiceProfileId'=> 'Profil ID',
    'SHOP_MODULE_sRPSwitzerlandInvoiceSecret'   => 'Security Code',
    'SHOP_MODULE_blRPNetherlandInvoice'         => 'RatePAY Rechnung aktiv',
    'SHOP_MODULE_blRPNetherlandInvoiceSandbox'  => 'Sandbox (Testmodus)',
    'SHOP_MODULE_sRPNetherlandInvoiceProfileId' => 'Profil ID',
    'SHOP_MODULE_sRPNetherlandInvoiceSecret'    => 'Security Code',
    'SHOP_MODULE_blRPNetherlandElv'             => 'RatePAY SEPA-Lastschrift aktiv',
    'SHOP_MODULE_blRPNetherlandElvSandbox'      => 'Sandbox (Testmodus)',
    'SHOP_MODULE_sRPNetherlandElvProfileId'     => 'Profil ID',
    'SHOP_MODULE_sRPNetherlandElvSecret'        => 'Security Code',
    'PI_RATEPAY_CONFIGTEST_INVOICE'             => 'Verbindungstest für RatePAY Rechnung',
    'PI_RATEPAY_CONFIGTEST_INSTALLMENT'         => 'Verbindungstest für RatePAY Ratenzahlung',
    'PI_RATEPAY_CONFIGTEST_ELV'                 => 'Verbindungstest für RatePAY SEPA-Lastschrift',
    'PI_RATEPAY_RATEPAY'                       => 'RatePAY',
    'PI_RATEPAY_RECHNUNG'                      => 'RatePAY Rechnung',
    'PI_RATEPAY_ELV'                           => 'RatePAY SEPA-Lastschrift',
    'PI_RATEPAY_RATE'                          => 'RatePAY Rate',
    'PI_RATEPAY_DETAILS'                       => 'Details',
    'PI_RATEPAY_WHITELABEL'                    => "Whitelabel",
    'PI_RATEPAY_LOGGING'                       => "Logging",
    'PI_RATEPAY_LOGGING_ENTRY'                 => "Logentry",
    'PI_RATEPAY_LOGGING_ID'                    => "ID",
    'PI_RATEPAY_LOGGING_ORDERNUMBER'           => "Ordernumber",
    'PI_RATEPAY_LOGGING_TRANSACTIONID'         => "Transactionnumber",
    'PI_RATEPAY_LOGGING_PAYMENTMETHOD'         => "Paymentmethod",
    'PI_RATEPAY_LOGGING_PAYMENTTYPE'           => "Paymenttyp",
    'PI_RATEPAY_LOGGING_PAYMENTSUBTYPE'        => "Paymentsubtype",
    'PI_RATEPAY_LOGGING_RESULT_CODE'           => "Result-Code",
    'PI_RATEPAY_LOGGING_FIRST_NAME'            => "Name",
    'PI_RATEPAY_LOGGING_LAST_NAME'             => "Surname",
    'PI_RATEPAY_LOGGING_RESULT'                => "Result",
    'PI_RATEPAY_LOGGING_REQUEST'               => "Request",
    'PI_RATEPAY_LOGGING_RESPONSE'              => "Response",
    'PI_RATEPAY_LOGGING_DATE'                  => "Date",
    'PI_RATEPAY_LOGGING_DAYS'                  => "Days",
    'PI_RATEPAY_LOGGING_DELETE'                => "Delete",
    'PI_RATEPAY_LOGGING_DELETE_CONFIRM'        => "Are you sure that you want to delete all logentries older than ",
    'PI_RATEPAY_LOGGING_DELETE_CONFIRM2'       => " days?",
    'PI_RATEPAY_LOGGING_TEXTDAYS'              => "Delete all entries whichare older than ",
    'PI_RATEPAY_LOGGING_SUCCESS'               => "Deleting was successfull.",
    'PI_RATEPAY_NODETAILS'                     => 'No RatePAY Payment.',
    'PI_RATEPAY_CONNECTED'                     => 'Connected',
    'PI_RATEPAY_DISCONNECTED'                  => 'Not connected',
    'PI_RATEPAY_UNAVAILABLE'                   => 'Not available',
    'PI_RATEPAY_ARTICLENR'                     => "Art.-No.",
    'PI_RATEPAY_ARTICLENAME'                   => "Description",
    'PI_RATEPAY_UNITPRICE'                     => "Unitprice (Netto)",
    'PI_RATEPAY_TOTALPRICE'                    => "Totalprice (Brutto)",
    'PI_RATEPAY_ORDERED'                       => "Ordered",
    'PI_RATEPAY_SHIPPED'                       => "Delivered",
    'PI_RATEPAY_CANCELLED'                     => "Cancelled",
    'PI_RATEPAY_RETURNED'                      => "Returned",
    'PI_RATEPAY_TAX'                           => "Tax",
    'PI_RATEPAY_QUANTITY'                      => "Quantity",
    'PI_RATEPAY_SHIPPING'                      => "ship",
    'PI_RATEPAY_CANCELLING'                    => "cancel",
    'PI_RATEPAY_KOMMA'                         => ",",
    'PI_RATEPAY_RETURNING'                     => "return",
    'PI_RATEPAY_RETURNING_TABLE_HEAD'          => "Retoure",
    'PI_RATEPAY_VOUCHER'                       => "create Voucher",
    'PI_RATEPAY_HISTORY'                       => "History",
    'PI_RATEPAY_CONFIRMDELIVER'                => "Delivery",
    'PI_RATEPAY_SHIPPING_TABLE_HEAD'           => "Delivery/Cancellation",
    'PI_RATEPAY_GOODWILL'                      => "Voucher",
    'PI_RATEPAY_RETURN'                        => "Return",
    'PI_RATEPAY_CANCELLATION'                  => "Cancellation",
    'PI_RATEPAY_PARTIALRETURN'                 => "Partial return",
    'PI_RATEPAY_FULLRETURN'                    => "Full return",
    'PI_RATEPAY_PARTIALCANCELLATION'           => "Partial cancellation",
    'PI_RATEPAY_FULLCANCELLATION'              => "Full cancellation",
    'PI_RATEPAY_ACTION'                        => "Action",
    'PI_RATEPAY_DATE'                          => "Date",
    'PI_RATEPAY_SUCCESSPARTIALCANCELLATION'    => "Part cancellation was successfull.",
    'PI_RATEPAY_SUCCESSFULLCANCELLATION'       => "Complete cancellation was successfull.",
    'PI_RATEPAY_SUCCESSPARTIALRETURN'          => "Part return was successfull.",
    'PI_RATEPAY_SUCCESSFULLRETURN'             => "Complete return was successfull.",
    'PI_RATEPAY_SUCCESSDELIVERY'               => "Delivery was successfull.",
    'PI_RATEPAY_SUCCESSVOUCHER'                => "Voucher was successfull.",
    'PI_RATEPAY_ERRORPARTIALCANCELLATION'      => "Part cancellation was not successfull.",
    'PI_RATEPAY_ERRORFULLCANCELLATION'         => "Complete cancellation was not successfull.",
    'PI_RATEPAY_ERRORPARTIALRETURN'            => "Part return was not successfull.",
    'PI_RATEPAY_ERRORFULLRETURN'               => "Complete return was not successfull.",
    'PI_RATEPAY_ERRORDELIVERY'                 => "Delivery was not successfull.",
    'PI_RATEPAY_ERRORVOUCHER'                  => "Voucher was not successfull.",
    'PI_RATEPAY_ERRORTYPING'                   => "Wrong input. Input was reseted. Please provide only numbers, which are not exceeding the prefilled value.",
    'PI_RATEPAY_ADMIN_MENU_CONFIGURATION'      => "Installment Configuration",
    'PI_RATEPAY_ADMIN_MENU_PROFILES'           => "Profiles",
    'PI_RATEPAY_PROFILE_DETAILS'               => "Profile details",
    'PI_RATEPAY_RECHNUNG_SETTINGS_DUEDATE'     => "Due in",
    'PI_RATEPAY_RECHNUNG_SETTINGS_DUEDATE_DAY' => "Days",
    'PI_RATEPAY_RATE_PAYMENTFIRSTDAY'          => "Activate payment due date for customer",
    'PI_RATEPAY_ELV_SETTINGS'                  => "Lastschrift Einstellungen",
    'PI_RATEPAY_ELV_SETTINGS_TITLE'            => "RatePAY SEPA-Lastschrift Einstellungen",
    'PI_RATEPAY_SAVEBANKDATA'                  => "Save bank data (encrypted)",
    'PI_RATEPAY_ACTIVATE_ELV'                  => "Lastschrift für Rate aktivieren"
);
